### ISSUE TITLE
Missing utils & tests

### ISSUE THREAD

**Issue by Pascal66** [evgenius1424/trie-anagrams#1]
Sorry, I'm not understand the logic 👯‍♂️ 
Why I've to put à my random string in the trie, to search for all the subanagram ?
Missing a getAllSubAnagram(random String) from the already done trie ?

**Comment by evgenius1424** [comment]
Hi, I did not get your task. 

The goal of my task is to determine that provided (as input) word is anagram or subanagram of another word in dictionary. 

We put whole dictionary in trie to speed up this check for each word.

**Comment by Pascal66** [comment]
As I see, I've to put my random string in the dictionary. 
As I ask, can I do getAllSubAnagram from it ?

**Comment by evgenius1424** [comment]
It is not implemented, but it is possible. 

You may explore trie for that

e.g. if your dictionary contains only two words - cat and category, you need to explore a-c node to find subanagram cat for word category. 

I'm not sure that it is the best solution (for your task), but it will work.

**Comment by Pascal66** [comment]
It's ok @evgenius1424, just trying to improve your way.

**Comment by evgenius1424** [comment]
Okay. 

getAllSubAnagram(word) - this method does not solve my initial task. 

Do you want to improve my solution or complete your own similar task?

Can you share your task in this case, it sounds interesting.

**Comment by evgenius1424** [comment]
@Pascal66 The goal of this puzzle is to take a large dictionary (let's say an English dictionary) and remove all the anagrams and subanagrams from it. The current logic is already implemented, so I'll close the topic. Thanks for contacting me.
